baseURL: "https://ndieckow.github.io/"
languageCode: "en-us"
title: Thoughts about Life and AI
theme: stack
copyright: Niklas Dieckow

params:
  homeInfoParams:
    Title: Niklas' Blog
    Content: On this blog, I'll share what I'm currently working on and thinking about.

  socialIcons: # optional
    - name: GitHub
      url: "https://github.com/ndieckow"
  
  showReadingTime: true

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

outputs:
  home:
    - HTML
    - RSS
    - JSON