baseURL: "https://ndieckow.github.io/"
languageCode: "en-us"
title: Thoughts about Life and AI
theme: papermod
copyright: Niklas Dieckow

params:
  homeInfoParams:
    Title: Welcome to my blog
    Content: This is a collection of thoughts and ideas of a twenty-something PhD student in artificial intelligence. Expect AI-focused topics, but also personal topics such as learned lessons that I would like to share.

  socialIcons: # optional
    - name: GitHub
      url: "https://github.com/ndieckow"
  
  showReadingTime: true

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

outputs:
  home:
    - HTML
    - RSS
    - JSON